
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.minic.analisadorsintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 27;
  public static final int CHAR = 6;
  public static final int SOMA = 24;
  public static final int ABRE_CHAVE = 32;
  public static final int LITERAL_PONTO_FLUTUANTE = 39;
  public static final int DIFERENTE = 22;
  public static final int DOUBLE = 5;
  public static final int FECHA_CHAVE = 33;
  public static final int LETRA_H = 36;
  public static final int INT = 3;
  public static final int VIRGULA = 31;
  public static final int NEGACAO = 23;
  public static final int PONTO = 29;
  public static final int IDENTIFICADOR = 37;
  public static final int IGUAL = 20;
  public static final int PRINTSTR = 15;
  public static final int DIV = 26;
  public static final int MAIN = 8;
  public static final int IF = 10;
  public static final int PRINTINT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int PONTO_VIRGULA = 30;
  public static final int MAIOR = 19;
  public static final int ABRE_PARENTESES = 34;
  public static final int error = 1;
  public static final int INCLUDE = 7;
  public static final int LITERAL_CHAR = 40;
  public static final int MENOR = 17;
  public static final int VOID = 2;
  public static final int LITERAL_INTEIRO = 38;
  public static final int PRINTF = 13;
  public static final int JOGO_DA_VELHA = 28;
  public static final int ELSE = 11;
  public static final int LITERAL_STRING = 41;
  public static final int WHILE = 12;
  public static final int FECHA_PARENTESES = 35;
  public static final int FLOAT = 4;
  public static final int ATRIBUICAO = 21;
  public static final int MENOR_IGUAL = 16;
  public static final int SUB = 25;
  public static final int MAIOR_IGUAL = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "FLOAT",
  "DOUBLE",
  "CHAR",
  "INCLUDE",
  "MAIN",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTF",
  "PRINTINT",
  "PRINTSTR",
  "MENOR_IGUAL",
  "MENOR",
  "MAIOR_IGUAL",
  "MAIOR",
  "IGUAL",
  "ATRIBUICAO",
  "DIFERENTE",
  "NEGACAO",
  "SOMA",
  "SUB",
  "DIV",
  "MULT",
  "JOGO_DA_VELHA",
  "PONTO",
  "PONTO_VIRGULA",
  "VIRGULA",
  "ABRE_CHAVE",
  "FECHA_CHAVE",
  "ABRE_PARENTESES",
  "FECHA_PARENTESES",
  "LETRA_H",
  "IDENTIFICADOR",
  "LITERAL_INTEIRO",
  "LITERAL_PONTO_FLUTUANTE",
  "LITERAL_CHAR",
  "LITERAL_STRING"
  };
}

